# Generated by Django 6.1 on 2026-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
