# Generated by Django 6.1 on 2026-09-24 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_name_subject_subject_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_name'], name='subjects_su_subject_1fe0db_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['teacher'], name='subjects_su_teacher_eb8ffe_idx'),
        ),
    ]
