# Generated by Django 6.1 on 2026-09-24 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_mark_student'),
        ('subjects', '0003_subject_subjects_su_subject_1fe0db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student', 'subject'], name='marks_mark_student_af4461_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student'], name='marks_mark_student_a2382d_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['subject'], name='marks_mark_subject_da6608_idx'),
        ),
    ]
