# Generated by Django 6.1 on 2026-09-25 17:29

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_mark_marks_mark_student_af4461_idx_and_more'),
        ('subjects', '0003_subject_subjects_su_subject_1fe0db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mark',
            name='class_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='mark',
            name='homework',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='mark',
            name='monthly_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='mark',
            name='period',
            field=models.CharField(choices=[('week_1', 'Week 1'), ('week_2', 'Week 2'), ('week_3', 'Week 3'), ('week_4', 'Week 4'), ('week_5', 'Week 5'), ('week_6', 'Week 6'), ('week_7', 'Week 7'), ('week_8', 'Week 8'), ('week_9', 'Week 9'), ('week_10', 'Week 10'), ('week_11', 'Week 11'), ('week_12', 'Week 12'), ('week_13', 'Week 13'), ('week_14', 'Week 14'), ('week_15', 'Week 15'), ('week_16', 'Week 16'), ('month_1_exam', 'Month 1 Exam'), ('month_2_exam', 'Month 2 Exam')], default='week_1', max_length=20),
        ),
        migrations.AddField(
            model_name='mark',
            name='weekly_assessment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'period')},
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student', 'subject', 'period'], name='marks_mark_student_bab929_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['period'], name='marks_mark_period_637e09_idx'),
        ),
    ]
